package config

import (
	"errors"
	"fmt"
	"os"
)

// DefaultFileName is the portable no-argument startup configuration.
const DefaultFileName = "config.yaml"

const defaultFileContents = `# Generated by OpsPilot. Restart the application after changing this file.
listen_address: 0.0.0.0:8080
data_dir: .data
database_path: .data/ops-agent.db
policy_path: ""

web_auth:
  # The initial password is printed once in the startup window, never saved here.
  secure_cookies: false

workspace_dir: workspace
workspace_sandbox_path: bwrap

validators: []

logging:
  level: info
  format: text
  file: .data/ops-agent.log
  add_source: false
  max_size_mb: 20
  max_backups: 3
  recent_limit: 2000

ssh:
  default_known_hosts: .data/known_hosts

model:
  base_url: ""
  name: gpt-4o-mini

limits:
  sync_timeout_seconds: 60
  max_timeout_seconds: 600
  max_output_bytes: 10485760
  model_output_bytes: 32768
  global_concurrency: 8
  host_concurrency: 2
`

// EnsureDefaultFile creates a user-editable configuration without replacing
// an existing file. Secrets are deliberately excluded.
func EnsureDefaultFile(path string) (bool, error) {
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if errors.Is(err, os.ErrExist) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("create default configuration: %w", err)
	}
	removeIncomplete := true
	defer func() {
		_ = file.Close()
		if removeIncomplete {
			_ = os.Remove(path)
		}
	}()
	if _, err := file.WriteString(defaultFileContents); err != nil {
		return false, fmt.Errorf("write default configuration: %w", err)
	}
	if err := file.Sync(); err != nil {
		return false, fmt.Errorf("sync default configuration: %w", err)
	}
	if err := file.Close(); err != nil {
		return false, fmt.Errorf("close default configuration: %w", err)
	}
	removeIncomplete = false
	return true, nil
}
